#!/bin/bash

# This program un-comments out prepended DNS resolvers so they will be used
# glibc/libc resolver will only use the first three nameservers. 
# useful for network debugging; needs sudo
#       - Cole Hocking

echo "Prepending 3 DNS Servers..."

# Un-comment the 'prepend nameserver' line in dhclinet.conf 
sudo sed -e 's/#prepend domain-name-servers/prepend domain-name-servers/g' /etc/dhcp/dhclient.conf -i

# Restart the network-manager for the changes to take effect
sudo service network-manager restart

# give the network-manager a couple seconds to restart
sleep 4

# Make sure that it worked
cat /etc/resolv.conf
